### ISSUE TITLE
can't start the project

### ISSUE THREAD

**Issue by johanetox** [timberio/molecule#19]
`yarn electron` just opens an blank window, tried `npm start` but doesn't work either

**Comment by zsherman** [comment]
@johanetox can you provide a little more detail here? It could be clearer in the docs but you need to have the dev server running before electron will work in development.

Try running:

`yarn start`

and in another tab

`yarn electron`

and let me know if you still see issues.

**Comment by zsherman** [comment]
Going to close this for now, if it still persists please let me know and I'll reopen.
