### ISSUE TITLE
Building for web target?

### ISSUE THREAD

**Issue by Slapbox** [timberio/molecule#20]
Awesome work as I mentioned already! I'm wondering how you would build a production copy for the web using this boilerplate?

**Comment by zsherman** [comment]
thanks @Slapbox! Good to hear from you again, super easy:

`yarn build`

and everything gets compiled to a `dist` folder for you which you can serve statically or run a simple server on top of. Run `yarn serve:dist` to see an example server running on the dist folder after building.

**Comment by Slapbox** [comment]
Thanks very much @zsherman!
