### ISSUE TITLE
Loading incorrect project into electron window.

### ISSUE THREAD

**Issue by aaronschwartz** [timberio/molecule#5]
Steps to reproduce:

1. Run a webpack project on port 3000.
2. In molecule run `yarn dev`
3. In molecule (separate terminal) run `yarn electron`

Results:
I do not see the counter app loaded in the electron window. Instead I see my project that I previously had running on port 3000.

**Comment by zsherman** [comment]
Previously we were using browsersync to run the dev server, but since we switch to the webpack dev server this should no longer happen. If you have something else running on that port it will warn you. Closing for now but I'll open https://github.com/timberio/molecule/issues/11.
